# Generated by Django 3.1 on 2020-12-05 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearn', '0002_auto_20201205_0558'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
