# Generated by Django 3.1 on 2020-12-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearn', '0003_auto_20201205_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instructor',
            field=models.BooleanField(default=False),
        ),
    ]
