# Generated by Django 3.1 on 2020-12-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearn', '0004_user_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='instructor',
            new_name='is_instructor',
        ),
    ]
