# Generated by Django 3.1 on 2020-12-05 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearn', '0012_auto_20201205_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2020, 12, 5, 13, 54, 43, 479189, tzinfo=utc)),
        ),
    ]
