# Generated by Django 3.1 on 2020-12-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearn', '0015_auto_20201205_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='twitter',
        ),
        migrations.AddField(
            model_name='user',
            name='header',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
