# Generated by Django 3.1 on 2020-12-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearn', '0019_auto_20201206_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='score',
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
