# Generated by Django 3.1 on 2020-12-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearn', '0023_auto_20201206_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
