# Generated by Django 3.1 on 2020-12-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearn', '0025_auto_20201206_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'video'), ('1', 'quiz'), ('2', 'information')], default='0', max_length=50),
        ),
    ]
