# Generated by Django 3.1 on 2020-12-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearn', '0026_auto_20201207_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='information',
            field=models.TextField(blank=True),
        ),
    ]
