# Generated by Django 3.1 on 2020-12-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearn', '0027_lecture_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
