# Generated by Django 3.1 on 2020-12-08 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearn', '0028_exam_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(blank=True, related_name='category', to='OnlineLearn.SubCategory'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='nouser.jpg', null=True, upload_to=''),
        ),
    ]
