# Generated by Django 3.1 on 2020-12-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearn', '0030_auto_20201208_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='taken_courses',
            field=models.ManyToManyField(blank=True, related_name='users', to='OnlineLearn.Course'),
        ),
    ]
