# Generated by Django 3.1 on 2020-12-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearn', '0031_user_taken_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='no_image.jpg', null=True, upload_to=''),
        ),
    ]
