# Generated by Django 3.1 on 2020-12-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearn', '0032_auto_20201209_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_in_minute',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
