# Generated by Django 3.1 on 2020-12-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearn', '0033_auto_20201210_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
    ]
