# Generated by Django 3.1 on 2020-12-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearn', '0034_auto_20201210_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='category',
            name='profile_pic',
            field=models.ImageField(default='nouser.jpg', upload_to='category_image'),
        ),
    ]
