# Generated by Django 3.1 on 2020-12-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearn', '0036_auto_20201214_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
