# Generated by Django 3.1 on 2020-12-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLearn', '0037_auto_20201214_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_search_query',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
