from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name = 'index'),
    path('login', views.login_view, name = 'login'),
    path('logout', views.logout_view, name = 'logout'),
    path('register', views.register_view, name = 'register'),
    path('profile/<str:profile_email>', views.viewProfile, name = 'viewProfile'),
    path('profile/<str:profile_email>/edit', views.editProfile, name = 'editProfile'),
    path('reviewexam/<str:exam_id>', views.reviewExam, name = 'reviewExam'),
    path('course/<str:course_id>/submitexam/<str:exam_id>/lecture/<str:lecture_id>', views.submitExam, name = 'submitExam'),
    path('course/<str:course_id>/content/<str:lecture_id>', views.courseContent, name = 'coursecontent'),
    path('course/<str:course_id>/content/<str:lecture_id>/startquiz', views.courseContentStartQuiz, name = 'startquiz'),
    path('exam/<str:exam_id>/question/<str:question_id>/answer/<str:answer_id>/saved/', views.saveAnswer, name = 'saveAnswer'),
    path('exam/<str:exam_id>/question/<str:question_id>/check/', views.checkAnswer, name = 'checkAnswer'),
    path('notfound', views.notfound, name = 'notfound'),
    path("course/content/qa/<str:course_id>", views.getCourseQAForm, name="qa_form"),
    path('course/content/addquestion/<str:course_id>', views.addQuestionToForm, name='addquestion'),
    path('course/content/addanswer/<str:question_id>', views.addAnswerToForm, name='addanswer'),
    path('category/<str:category_id>', views.getSubCategory, name = 'subcategory'),
    path('instructor/dashboard', views.instructorDashboard, name = 'instructorDashboard'),
    path('course/<str:course_id>/addcontent', views.addContent, name = 'addcontent'),
    path('course/<str:course_id>/editsection/<str:section_id>', views.editSection, name = 'editsection'),
    path('course/<str:course_id>/addlecture/<str:section_id>', views.addLecture, name = 'addlecture'),
    path('course/<str:course_id>/editlecture/<str:lecture_id>', views.editLecture, name = 'editlecture'),
    path('course/<str:course_id>/addquestion/<str:quiz_id>', views.addQuestion, name = 'addquestion'),
    path('course/<str:course_id>/deletelecture/<str:lecture_id>', views.deleteLecture, name = 'deletelecture'),
    path('course/<str:course_id>/deletesection/<str:section_id>', views.deleteSection, name = 'deletesection'),
    path('course/<str:course_id>/delete', views.deleteCourse, name = 'deletecourse'),
    path('course/<str:course_id>/description', views.course, name = 'course'),
    path('search', views.search, name='search'),
    path('course/<str:course_id>/enroll', views.enroll, name = 'enroll'),
    path('search/query/<str:query>', views.searchAPI, name = 'searchAPI'),
]
